jobs:
  compatibility:
    name: ${{ matrix.branch }} - ${{ matrix.spring }} ${{ matrix.kotlin }} ${{ matrix.jackson
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out sources
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: List dependencies
      run: ./mvnw -D depedency:list -Dsort
    - continue-on-error: true
      name: Build
      run: ./mvnw -B verify -P${{ matrix.spring }},${{ matrix.kotlin }},${{ matrix.jackson
        }} --file pom.xml
    strategy:
      matrix:
        branch:
        - main
        - 2.2.x
        - 2.1.x
        jackson:
        - ''
        - jackson-next
        kotlin:
        - ''
        - kotlin-next
        - kotlin-2-next
        spring:
        - ''
        - spring-next
        - spring-61-next
name: Compatibility builds
on:
  repository_dispatch:
    types: trigger-ga___compatibility.yaml
