jobs:
  build:
    name: Release project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out sources
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B
    - continue-on-error: true
      env:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      name: Deploy to Artifactory
      run: ./mvnw -B clean deploy -Pci,artifactory
    - continue-on-error: true
      name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - continue-on-error: true
      env:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      name: Deploy documentation
      run: ./mvnw -B clean deploy -Pdocumentation
name: Release Milestones
on:
  repository_dispatch:
    types: trigger-ga___milestone.yaml
